POST http://localhost:8080/api/v1/sensor-data/scd30
Content-Type: application/json

{
  "co2": {
    "value": 2311,
    "units": "ppm"
  },
  "temperature": {
    "value": 34.8,
    "units": "C"
  },
  "humidity": {
    "value": 48.8,
    "units": "%"
  }
}

###
GET http://localhost:8080/api/v1/sensor-data/scd30?types=co2,temperature

###
GET http://localhost:8080/api/v1/sensor-data/average/scd30/co2?duration=60000

###
GET http://localhost:8080/api/v1/sensor-data/subscribe/scd30/co2?duration=60000

###
GET http://localhost:8080/api/v1/sensor-data/scd30?types=co2&from=2023-05-28T23:08:00.000-05:00